### ISSUE TITLE
想请问一下基准轨迹和抖动轨迹如何得到

### ISSUE THREAD

**Issue by xishandong** [ksy2019/jd-login#1]
我自己也在浏览器上滑动了这两个，但是生成的轨迹验证是错误的，请问您是如何滑动这两个轨迹的

**Comment by suke1998** [comment]
轨道A: 0px - 300px  比较线性的轨道
轨道B: 0px -100px - 0px 晃动的轨道 
假设目标位置 160px
截取A 0px - 160; 得到轨道C
遍历轨道B，每个节点的X轴添加160px; 将B插入C

大概是这么个思路；比较麻烦；不推荐这个方案了；目前写了一个生成滑轨的方法，成功率比较高；
