### ISSUE TITLE
萌新小白求助

### ISSUE THREAD

**Issue by MicroMatrixOrg** [ksy2019/jd-login#2]
大佬，这个代码的逻辑是什么啊。我之前用cv2写了个匹配图像然后移动的算法，但是一直移动不上去。你这个代码的逻辑是啥啊。我不是很懂js和py之间的关系

**Comment by suke1998** [comment]
js和python的关系：
这个脚本本身是nodejs，有一个朋友写了个python的，就弄上来了，本质上是python调用v8运行js；更推荐直接使用nodejs；
代码逻辑；生成滑轨并调用验证接口，js生成滑轨，python调用验证接口
